[colors.primary]
background = "#1e282d"
foreground = "#c4c7d1"

[colors.normal]
black = "#666666"
red = "#eb606b"
green = "#c3e88d"
yellow = "#f7eb95"
blue = "#54B5AB"
magenta = "#ff2f90"
cyan = "#aeddff"
white = "#ffffff"

[colors.bright]
black = "#ff262b"
red = "#eb606b"
green = "#c3e88d"
yellow = "#f7eb95"
blue = "#54B5AB"
magenta = "#6c71c4"
cyan = "#35434d"
white = "#ffffff"

[window]
startup_mode = "Maximized"
dynamic_title = false

[font]
normal = { family = "Fira Code Nerd Font" }
size = 13.0
