[colors.primary]
background = "#1c1c2b"
foreground = "#c4c7d1"

[colors.normal]
black = "#666666"
red = "#eb606b"
green = "#c3e88d"
yellow = "#f7eb95"
blue = "#54B5AB"
magenta = "#ff2f90"
cyan = "#aeddff"
white = "#ffffff"

[colors.bright]
black = "#ff262b"
red = "#eb606b"
green = "#c3e88d"
yellow = "#f7eb95"
blue = "#54B5AB"
magenta = "#6c71c4"
cyan = "#35434d"
white = "#ffffff"

[window]
dimensions = { columns = 155, lines = 44 }
dynamic_title = false
decorations = "None"

[font]
normal = { family = "Hack Nerd Font" }
size = 13.0
